#!/usr/bin/env python3
"""Restores the Q1 page's "where is the money going, and to whom" breakdowns
(flow-type totals, destination totals, top recipients) that lived as
hand-typed Markdown tables until 2026-08-27's graph cutover -- now computed
live from the graph and rendered through the site's existing claim-receipt
page (layouts/claim/single.html), so every number is a click away from its
sources, per Ben: "each one a clickable claim that takes one to a page that
breaks down where the figure came from."

Writes theprojection-site/data/q1_claims.json: a flat list of claim objects
in the SAME shape data/claims.json already uses (id/subject/dimension/
label/value/basis/confidence/as_of/sources, or aggregate+members) -- kept
in a separate file rather than injected into data/claims.json because that
file is entirely regenerated by publish/adapter.py::build_claims() from
board.yaml provenance bundles on every `kestrel publish`, which would wipe
out anything written here. layouts/claim/single.html reads both files, and
one content/claim/<id>.md stub per id (leaf + aggregate) is written here so
Hugo routes /claim/<id>/ for each -- ids are prefixed `q1-` so they can
never collide with a bundle-derived id.

Universe: every claim atom referenced as a `materialized_from_claim_ref(s)`
of a `funds` relationship in graph/relationships.jsonl -- the same flow
observations graph/export_q1.py draws its edges from. Aggregate totals sum
only claims with quantity_basis "point" and quantity_unit "USD"; a claim
recorded as an estimate/ceiling/floor still appears as a member (nothing
hidden) but isn't summed into the headline total, and the count of each is
reported so the gap is visible rather than silently absorbed.
"""
import json, os, re
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SITE = os.path.join(os.path.dirname(REPO), "theprojection-site")
OUT = os.path.join(SITE, "data", "q1_claims.json")
# NOT content/claim/ -- publish/adapter.py prunes that directory to exactly
# the ids in its own claims.json on every `kestrel publish` run (deletes
# anything else there but _index.md), which silently deleted every one of
# these stubs the first time /week or a manual publish ran after they were
# created (live 404s, caught 2026-08-27). content/q1claim/ is a directory
# adapter.py never touches; each stub's `type: claim` front matter tells
# Hugo to still render it with layouts/claim/single.html.
STUB_DIR = os.path.join(SITE, "content", "q1claim")

RELIABILITY_BAND = {
    # A stand-in until cloud-researcher's own reliability_tier machinery
    # lands (graph/DESIGN.md Appendix A2) -- the graph only carries the
    # coarser `evidence_class` today. Documented here, not silently guessed.
    "published_document": "high",
    "testimony_disinterested": "high",
    "testimony_interested": "med",
}


def read(fname):
    p = os.path.join(HERE, fname)
    return [json.loads(l) for l in open(p) if l.strip()]


atoms = read("atoms.jsonl")
rels = read("relationships.jsonl")
sources = read("sources.jsonl")
atom_by_id = {a["knowledge_atom_id"]: a for a in atoms if "knowledge_atom_id" in a}
source_by_id = {s["source_id"]: s for s in sources}
part_of = {r["source_ref"]: r["target_ref"] for r in rels if r["predicate_id"] == "part_of"}


def strip(ref):
    return ref.split(":", 1)[1] if isinstance(ref, str) and ":" in ref else ref


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", str(s).lower()).strip("-")


def canonical(aid):
    canon_ref = part_of.get(f"knowledge_atom:{aid}")
    if canon_ref:
        c = atom_by_id.get(strip(canon_ref))
        if c:
            return c.get("meta", {}).get("entity_slug", aid), c.get("label", c.get("name"))
    a = atom_by_id.get(aid, {})
    return a.get("meta", {}).get("entity_slug", aid), a.get("label", a.get("name", aid))


def real_world_actor(aid):
    """Which real-world company/actor this ENTITY facet belongs to, for
    testing whether two facets are the SAME actor (self-funded capex) --
    NOT via `part_of` (a canonical-entity link many facets never got
    created for, found 2026-08-27: e.g. neither Amkor's nor Micron's
    facets have one, so comparing part_of targets silently missed most
    same-company cases). `meta.entity_slug` is on every q1 facet atom
    unconditionally and is the actually-reliable "who is this" key.

    Callers MUST also check atom_type == "entity" before comparing two of
    these -- an `event` atom (a financing round) carries entity_slug too,
    but it tags "this round is ABOUT company X", not "this round IS
    company X". Missing that distinction caused a second, worse bug the
    same day: every investor-syndicate round funding a company's own
    capital facet (real EXTERNAL money in) got mislabeled self-funded,
    because the round event's entity_slug matched the recipient's.
    """
    return atom_by_id.get(aid, {}).get("meta", {}).get("entity_slug", aid)


def is_entity(aid):
    return atom_by_id.get(aid, {}).get("atom_type") == "entity"


def strip_facet_suffix(label):
    """"Amkor Technology (advanced packaging/test facility construction)"
    -> "Amkor Technology" -- for the self-funded label's company name,
    which must NOT repeat a specific facet's own parenthetical (that's
    what made "Amkor Technology (...)'s own capital" read so oddly)."""
    idx = label.find(" (")
    return label[:idx] if idx > 0 else label


# Precomputed once: entity_slug -> its shortest (least facet-specific)
# known label, for the self-funded case's "{Company}'s own capital" phrasing.
_entity_display_by_slug = {}
for _a in atoms:
    if _a.get("atom_type") != "entity":
        continue
    _slug = _a.get("meta", {}).get("entity_slug")
    if not _slug:
        continue
    _name = strip_facet_suffix(_a.get("label", _a.get("name", _slug)))
    if _slug not in _entity_display_by_slug or len(_name) < len(_entity_display_by_slug[_slug]):
        _entity_display_by_slug[_slug] = _name


def company_display_name(entity_slug, fallback):
    return _entity_display_by_slug.get(entity_slug, fallback)


def fmt_amount(v):
    if v is None:
        return None
    if v >= 1e9:
        return "${:.1f}B".format(v / 1e9)
    if v >= 1e6:
        return "${:.1f}M".format(v / 1e6)
    return "${:,.0f}".format(v)


# ---- gather the flow-claim universe: every claim a `funds` edge cites ----
funds = [r for r in rels if r["predicate_id"] == "funds"]
flow_claim_ids = set()
edge_by_claim = {}
for r in funds:
    q = r.get("qualifiers", {})
    refs = q.get("materialized_from_claim_refs") or ([q["materialized_from_claim_ref"]] if "materialized_from_claim_ref" in q else [])
    for ref in refs:
        cid = strip(ref)
        flow_claim_ids.add(cid)
        edge_by_claim[cid] = r

claims_out = []
leaf_ids_by_flow_type, leaf_ids_by_destination, leaf_ids_by_recipient = {}, {}, {}
skipped_non_point = {"flow_type": {}, "destination": {}, "recipient": {}}

for cid in sorted(flow_claim_ids):
    c = atom_by_id.get(cid)
    if not c:
        continue
    edge = edge_by_claim[cid]
    recipient_id = strip(edge["target_ref"])
    source_id = strip(edge["source_ref"])
    # subject/grouping uses the CANONICAL entity (rolls TSMC's facets up into
    # one "TSMC" recipient bucket, links /map/tsmc/) -- but the flow's own
    # description must stay at FACET granularity, or two different facets of
    # the same company (e.g. TSMC's treasury arm funding TSMC's own fab
    # construction) both collapse to the same label and read as a nonsense
    # self-loop ("TSMC → TSMC"), which is exactly the distinction this
    # research question exists to preserve (money vs. physical buildout are
    # different questions -- see content/research/q1.md). Found 2026-08-27
    # when Ben spotted a run of entity->same-entity rows.
    recipient_slug, recipient_label = canonical(recipient_id)
    facet_label = lambda aid: atom_by_id.get(aid, {}).get("label", atom_by_id.get(aid, {}).get("name", aid))
    facet_activity = lambda aid: atom_by_id.get(aid, {}).get("meta", {}).get("activity") or facet_label(aid)
    source_label, target_label = facet_label(source_id), facet_label(recipient_id)

    # NOT self-funded, NOT internal -- Ben, correcting the last two passes
    # at this: "it's not really self-funded. Stuff was purchased. The
    # transaction wasn't money from TSMC to TSMC... Expenses are never
    # internal." Right: when a company spends capex, the cash leaves the
    # company and pays real external vendors, contractors, and labor --
    # this map's `funds` edge just happens to run from the company's own
    # treasury facet to its own construction/fab facet (a budget
    # allocation: "TSMC earmarked $X toward this project"), because the
    # source discloses that allocation but never names who TSMC then paid
    # with it. So this is a genuine external transaction with an
    # UNNAMED recipient, not a same-company transaction with no
    # recipient. Both the label and the recipient bucket below now say
    # exactly that -- the money is NOT credited back to the company as if
    # it received its own spend, which the two prior passes still did by
    # accident (recipient_slug stayed the company's own canonical slug).
    vendor_unspecified = (is_entity(source_id) and is_entity(recipient_id)
                          and real_world_actor(source_id) == real_world_actor(recipient_id))
    meta = c.get("meta", {})
    flow_type = meta.get("flow_type") or "unclassified"
    destination = meta.get("destination_category") or "unclassified"
    amount, unit, basis_kind = c.get("quantity"), c.get("quantity_unit"), c.get("quantity_basis")
    is_point_usd = basis_kind == "point" and unit == "USD"

    src_objs = []
    band = None
    for sid in c.get("sources", []):
        s = source_by_id.get(sid)
        if not s:
            continue
        eb = s.get("evidence_class")
        band = band or RELIABILITY_BAND.get(eb)
        src_objs.append({
            "title": s.get("title"),
            "url": s.get("locator") if str(s.get("locator", "")).startswith("http") else None,
            "figure": s.get("meta", {}).get("q1_figure_text"),
            "as_of": s.get("published_at"),
            "reliability": RELIABILITY_BAND.get(eb, "low"),
        })

    amount_str = fmt_amount(amount) if is_point_usd else (fmt_amount(amount) + " (" + basis_kind + ")" if amount else None)
    lead = (amount_str + " — " if amount_str else "") + (c.get("summary") or c.get("body") or "")
    if vendor_unspecified:
        # The company is the PAYER, not the recipient of its own spend --
        # "unnamed vendor(s)" is the honest stand-in for whoever actually
        # got paid (contractors, equipment makers, labor), which this
        # source just doesn't name. destination_category answers "what did
        # it buy" (the same land/shell&materials, memory & storage, etc.
        # vocabulary the page's "by what it bought" table already uses);
        # the facet activity stays as parenthetical detail on which
        # project, not the headline.
        company_name = company_display_name(real_world_actor(source_id), source_label)
        label = f"{company_name} → unnamed vendor(s) — {destination} ({facet_activity(recipient_id)})"
        lead += (" " if lead else "") + ("(paid to unnamed vendors/contractors — "
                                          "this source doesn't disclose who specifically got the money)")
        recipient_slug = f"{real_world_actor(source_id)}--unnamed-vendors"
        recipient_label = f"Unnamed vendors (via {company_name}'s capex)"
    else:
        label = f"{source_label} → {target_label}"
    leaf_id = "q1-" + cid
    epistemic_status = c.get("epistemic_status", "accepted")
    explains_claim = c.get("meta", {}).get("explains_claim")
    claims_out.append({
        "id": leaf_id,
        # None, not the company's own slug: a vendor_unspecified claim
        # isn't "about" the paying company in the board-page sense (it
        # didn't RECEIVE anything), so it shouldn't crumb/link to /map/
        # the way a real "about this actor" claim does.
        "subject": None if vendor_unspecified else recipient_slug,
        "dimension": "q1-flow",
        "label": label,
        "vendor_unspecified": vendor_unspecified,
        "epistemic_status": epistemic_status,
        "explains_claim": ("q1-" + explains_claim) if explains_claim else None,
        "value": lead,
        "basis": lead,
        "confidence": band or "low",
        "as_of": c.get("valid_from"),
        # raw number, not just the formatted `value` string, so a claim
        # page can render its aggregate parent's "pieces" as a real sortable
        # table instead of a bullet list -- null means no settled point
        # figure (still a member, just not summable), never a guess.
        "amount_usd": amount if is_point_usd else None,
        "sources": src_objs,
    })

    # Hypothesized claims (graph/ingest/11_q1_vendor_hypotheses.py -- Ben:
    # "What's everything we know about where this money went?") are
    # evidence ABOUT a slice of an already-tracked figure, not an
    # additional, separate flow -- summing them into flow-type/destination
    # totals would double-count against the parent claim they explain.
    # They still get their own recipient bucket (a real, different company
    # than the payer), which is exactly the point: showing "Arizona State
    # Land Department: $197.25M" as a genuine recipient, distinct from and
    # not netted against "Unnamed vendors (via TSMC's capex)".
    if epistemic_status != "hypothesized":
        leaf_ids_by_flow_type.setdefault(flow_type, []).append((leaf_id, amount if is_point_usd else None))
        leaf_ids_by_destination.setdefault(destination, []).append((leaf_id, amount if is_point_usd else None))
    leaf_ids_by_recipient.setdefault((recipient_slug, recipient_label), []).append((leaf_id, amount if is_point_usd else None))
    if not is_point_usd:
        if epistemic_status != "hypothesized":
            skipped_non_point["flow_type"][flow_type] = skipped_non_point["flow_type"].get(flow_type, 0) + 1
            skipped_non_point["destination"][destination] = skipped_non_point["destination"].get(destination, 0) + 1
        skipped_non_point["recipient"][recipient_slug] = skipped_non_point["recipient"].get(recipient_slug, 0) + 1

# Cross-reference pass: attach each hypothesis claim's own leaf id onto the
# ORIGINAL claim it explains, so that claim's page can show "here's what's
# separately been reported about where this went" without pretending the
# hypotheses are members that sum to its total (they aren't -- see above).
explained_by = {}
for c in claims_out:
    if c.get("explains_claim"):
        explained_by.setdefault(c["explains_claim"], []).append(c["id"])
for c in claims_out:
    if c["id"] in explained_by:
        c["hypothesized_recipients"] = explained_by[c["id"]]


def make_aggregate(agg_id, dimension, short_label, label, member_pairs, subject=None, skipped=0):
    total = sum(v for _, v in member_pairs if v is not None)
    n_summed = sum(1 for _, v in member_pairs if v is not None)
    if n_summed:
        value = f"{fmt_amount(total)} tracked across {n_summed} claim(s)"
    else:
        value = f"no settled point figure yet across {len(member_pairs)} claim(s)"
    if skipped:
        value += f" (+{skipped} more without a settled point figure — see members)"
    claims_out.append({
        "id": agg_id,
        "subject": subject,
        "dimension": dimension,
        "short_label": short_label,
        "label": label,
        "value": value,
        "total_usd": total,
        "member_count": len(member_pairs),
        "basis": f"Sum of point-figure, USD-denominated flow claims tagged {label} in the Q1 money-flow map.",
        "confidence": "",
        "as_of": "",
        "sources": [],
        "members": [mid for mid, _ in member_pairs],
        "aggregate": True,
    })


for flow_type, pairs in sorted(leaf_ids_by_flow_type.items()):
    make_aggregate(
        "q1-agg-flowtype-" + slugify(flow_type), "q1-flow-type", flow_type, f"Flow type · {flow_type}",
        pairs, skipped=skipped_non_point["flow_type"].get(flow_type, 0),
    )

for destination, pairs in sorted(leaf_ids_by_destination.items()):
    make_aggregate(
        "q1-agg-dest-" + slugify(destination), "q1-destination", destination, f"Destination · {destination}",
        pairs, skipped=skipped_non_point["destination"].get(destination, 0),
    )

for (recipient_slug, recipient_label), pairs in sorted(leaf_ids_by_recipient.items(), key=lambda kv: kv[0][1] or ""):
    make_aggregate(
        "q1-agg-recipient-" + slugify(recipient_slug), "q1-recipient", recipient_label, f"Tracked inflow · {recipient_label}",
        pairs, subject=recipient_slug, skipped=skipped_non_point["recipient"].get(recipient_slug, 0),
    )

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    json.dump(claims_out, f, indent=1, sort_keys=True)

os.makedirs(STUB_DIR, exist_ok=True)
current_ids = {c["id"] for c in claims_out}
removed = 0
for fname in os.listdir(STUB_DIR):
    if fname.endswith(".md") and fname[:-3] not in current_ids:
        os.remove(os.path.join(STUB_DIR, fname))
        removed += 1

written = 0
for c in claims_out:
    stub_path = os.path.join(STUB_DIR, c["id"] + ".md")
    if os.path.exists(stub_path):
        continue
    with open(stub_path, "w") as f:
        f.write(f"---\ntitle: {json.dumps(c['label'])}\nclaim_id: {c['id']}\ntype: claim\n---\n")
    written += 1

n_leaf = sum(1 for c in claims_out if not c.get("aggregate"))
n_agg = len(claims_out) - n_leaf
print(f"{n_leaf} leaf flow claims, {n_agg} aggregates "
      f"({len(leaf_ids_by_flow_type)} flow-type, {len(leaf_ids_by_destination)} destination, "
      f"{len(leaf_ids_by_recipient)} recipient) -> {OUT}; {written} new claim stub(s), "
      f"{removed} stale stub(s) removed, in {STUB_DIR}")
