#!/usr/bin/env python3
"""Restores the Q1 page's "where is the money going, and to whom" breakdowns
(flow-type totals, destination totals, top recipients) that lived as
hand-typed Markdown tables until 2026-08-27's graph cutover -- now computed
live from the graph and rendered through the site's existing claim-receipt
page (layouts/claim/single.html), so every number is a click away from its
sources, per Ben: "each one a clickable claim that takes one to a page that
breaks down where the figure came from."

Writes theprojection-site/data/q1_claims.json: a flat list of claim objects
in the SAME shape data/claims.json already uses (id/subject/dimension/
label/value/basis/confidence/as_of/sources, or aggregate+members) -- kept
in a separate file rather than injected into data/claims.json because that
file is entirely regenerated by publish/adapter.py::build_claims() from
board.yaml provenance bundles on every `kestrel publish`, which would wipe
out anything written here. layouts/claim/single.html reads both files, and
one content/claim/<id>.md stub per id (leaf + aggregate) is written here so
Hugo routes /claim/<id>/ for each -- ids are prefixed `q1-` so they can
never collide with a bundle-derived id.

Universe: every claim atom referenced as a `materialized_from_claim_ref(s)`
of a `funds` relationship in graph/relationships.jsonl -- the same flow
observations graph/export_q1.py draws its edges from. Aggregate totals sum
only claims with quantity_basis "point" and quantity_unit "USD"; a claim
recorded as an estimate/ceiling/floor still appears as a member (nothing
hidden) but isn't summed into the headline total, and the count of each is
reported so the gap is visible rather than silently absorbed.
"""
import json, os, re
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SITE = os.path.join(os.path.dirname(REPO), "theprojection-site")
OUT = os.path.join(SITE, "data", "q1_claims.json")
STUB_DIR = os.path.join(SITE, "content", "claim")

RELIABILITY_BAND = {
    # A stand-in until cloud-researcher's own reliability_tier machinery
    # lands (graph/DESIGN.md Appendix A2) -- the graph only carries the
    # coarser `evidence_class` today. Documented here, not silently guessed.
    "published_document": "high",
    "testimony_disinterested": "high",
    "testimony_interested": "med",
}


def read(fname):
    p = os.path.join(HERE, fname)
    return [json.loads(l) for l in open(p) if l.strip()]


atoms = read("atoms.jsonl")
rels = read("relationships.jsonl")
sources = read("sources.jsonl")
atom_by_id = {a["knowledge_atom_id"]: a for a in atoms if "knowledge_atom_id" in a}
source_by_id = {s["source_id"]: s for s in sources}
part_of = {r["source_ref"]: r["target_ref"] for r in rels if r["predicate_id"] == "part_of"}


def strip(ref):
    return ref.split(":", 1)[1] if isinstance(ref, str) and ":" in ref else ref


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", str(s).lower()).strip("-")


def canonical(aid):
    canon_ref = part_of.get(f"knowledge_atom:{aid}")
    if canon_ref:
        c = atom_by_id.get(strip(canon_ref))
        if c:
            return c.get("meta", {}).get("entity_slug", aid), c.get("label", c.get("name"))
    a = atom_by_id.get(aid, {})
    return a.get("meta", {}).get("entity_slug", aid), a.get("label", a.get("name", aid))


def fmt_amount(v):
    if v is None:
        return None
    if v >= 1e9:
        return "${:.1f}B".format(v / 1e9)
    if v >= 1e6:
        return "${:.1f}M".format(v / 1e6)
    return "${:,.0f}".format(v)


# ---- gather the flow-claim universe: every claim a `funds` edge cites ----
funds = [r for r in rels if r["predicate_id"] == "funds"]
flow_claim_ids = set()
edge_by_claim = {}
for r in funds:
    q = r.get("qualifiers", {})
    refs = q.get("materialized_from_claim_refs") or ([q["materialized_from_claim_ref"]] if "materialized_from_claim_ref" in q else [])
    for ref in refs:
        cid = strip(ref)
        flow_claim_ids.add(cid)
        edge_by_claim[cid] = r

claims_out = []
leaf_ids_by_flow_type, leaf_ids_by_destination, leaf_ids_by_recipient = {}, {}, {}
skipped_non_point = {"flow_type": {}, "destination": {}, "recipient": {}}

for cid in sorted(flow_claim_ids):
    c = atom_by_id.get(cid)
    if not c:
        continue
    edge = edge_by_claim[cid]
    recipient_id = strip(edge["target_ref"])
    recipient_slug, recipient_label = canonical(recipient_id)
    source_slug, source_label = canonical(strip(edge["source_ref"]))
    meta = c.get("meta", {})
    flow_type = meta.get("flow_type") or "unclassified"
    destination = meta.get("destination_category") or "unclassified"
    amount, unit, basis_kind = c.get("quantity"), c.get("quantity_unit"), c.get("quantity_basis")
    is_point_usd = basis_kind == "point" and unit == "USD"

    src_objs = []
    band = None
    for sid in c.get("sources", []):
        s = source_by_id.get(sid)
        if not s:
            continue
        eb = s.get("evidence_class")
        band = band or RELIABILITY_BAND.get(eb)
        src_objs.append({
            "title": s.get("title"),
            "url": s.get("locator") if str(s.get("locator", "")).startswith("http") else None,
            "figure": s.get("meta", {}).get("q1_figure_text"),
            "as_of": s.get("published_at"),
            "reliability": RELIABILITY_BAND.get(eb, "low"),
        })

    amount_str = fmt_amount(amount) if is_point_usd else (fmt_amount(amount) + " (" + basis_kind + ")" if amount else None)
    lead = (amount_str + " — " if amount_str else "") + (c.get("summary") or c.get("body") or "")
    leaf_id = "q1-" + cid
    claims_out.append({
        "id": leaf_id,
        "subject": recipient_slug,
        "dimension": "q1-flow",
        "label": f"{source_label} → {recipient_label}",
        "value": lead,
        "basis": lead,
        "confidence": band or "low",
        "as_of": c.get("valid_from"),
        "sources": src_objs,
    })

    leaf_ids_by_flow_type.setdefault(flow_type, []).append((leaf_id, amount if is_point_usd else None))
    leaf_ids_by_destination.setdefault(destination, []).append((leaf_id, amount if is_point_usd else None))
    leaf_ids_by_recipient.setdefault((recipient_slug, recipient_label), []).append((leaf_id, amount if is_point_usd else None))
    if not is_point_usd:
        skipped_non_point["flow_type"][flow_type] = skipped_non_point["flow_type"].get(flow_type, 0) + 1
        skipped_non_point["destination"][destination] = skipped_non_point["destination"].get(destination, 0) + 1
        skipped_non_point["recipient"][recipient_slug] = skipped_non_point["recipient"].get(recipient_slug, 0) + 1


def make_aggregate(agg_id, dimension, short_label, label, member_pairs, subject=None, skipped=0):
    total = sum(v for _, v in member_pairs if v is not None)
    n_summed = sum(1 for _, v in member_pairs if v is not None)
    if n_summed:
        value = f"{fmt_amount(total)} tracked across {n_summed} claim(s)"
    else:
        value = f"no settled point figure yet across {len(member_pairs)} claim(s)"
    if skipped:
        value += f" (+{skipped} more without a settled point figure — see members)"
    claims_out.append({
        "id": agg_id,
        "subject": subject,
        "dimension": dimension,
        "short_label": short_label,
        "label": label,
        "value": value,
        "total_usd": total,
        "member_count": len(member_pairs),
        "basis": f"Sum of point-figure, USD-denominated flow claims tagged {label} in the Q1 money-flow map.",
        "confidence": "",
        "as_of": "",
        "sources": [],
        "members": [mid for mid, _ in member_pairs],
        "aggregate": True,
    })


for flow_type, pairs in sorted(leaf_ids_by_flow_type.items()):
    make_aggregate(
        "q1-agg-flowtype-" + slugify(flow_type), "q1-flow-type", flow_type, f"Flow type · {flow_type}",
        pairs, skipped=skipped_non_point["flow_type"].get(flow_type, 0),
    )

for destination, pairs in sorted(leaf_ids_by_destination.items()):
    make_aggregate(
        "q1-agg-dest-" + slugify(destination), "q1-destination", destination, f"Destination · {destination}",
        pairs, skipped=skipped_non_point["destination"].get(destination, 0),
    )

for (recipient_slug, recipient_label), pairs in sorted(leaf_ids_by_recipient.items(), key=lambda kv: kv[0][1] or ""):
    make_aggregate(
        "q1-agg-recipient-" + slugify(recipient_slug), "q1-recipient", recipient_label, f"Tracked inflow · {recipient_label}",
        pairs, subject=recipient_slug, skipped=skipped_non_point["recipient"].get(recipient_slug, 0),
    )

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    json.dump(claims_out, f, indent=1, sort_keys=True)

os.makedirs(STUB_DIR, exist_ok=True)
written = 0
for c in claims_out:
    stub_path = os.path.join(STUB_DIR, c["id"] + ".md")
    if os.path.exists(stub_path):
        continue
    with open(stub_path, "w") as f:
        f.write(f"---\ntitle: {json.dumps(c['label'])}\nclaim_id: {c['id']}\n---\n")
    written += 1

n_leaf = sum(1 for c in claims_out if not c.get("aggregate"))
n_agg = len(claims_out) - n_leaf
print(f"{n_leaf} leaf flow claims, {n_agg} aggregates "
      f"({len(leaf_ids_by_flow_type)} flow-type, {len(leaf_ids_by_destination)} destination, "
      f"{len(leaf_ids_by_recipient)} recipient) -> {OUT}; {written} new claim stub(s) in {STUB_DIR}")
